project:
  type: website

website:
  title: "iandavis1937"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: quartz_custom.scss
    css: styles.css
    include-after-body: scroll_gradient.js
    toc: true

editor: visual

