project:
  type: website

website:
  title: "iandavis1937"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd

conda-env: personalwebenv

format:
  html:
    page-layout: custom
    grid:
        sidebar-width: 300px
        body-width: 900px
        margin-width: 300px
        gutter-width: 1.5rem
    theme: quartz_custom.scss
    fontcolor: "#fff"
    include-before-body: before_body.html
    toc: true
    toc-depth: 6
    toc-location: right
    
editor: source

