---
title: "CV"
format:
  html:
    page-layout: article
    theme: quartz_custom.scss
    css: styles.css
    fontcolor: "#fff"
    include-before-body: before_body.html
    toc: true
    toc-depth: 6
    toc-location: right
---

## Ian A. Davis

Philadelphia, PA      /      iandavis1937\@gmail.com      /      [iandavis1937.com](index.qmd)     /     [<i class="fab fa-linkedin"></i>](https://www.linkedin.com/in/ian-davis-b53364b1/)

### [Summary]{.underline}

Detail-oriented data storyteller & self-starter with a passion for advancing social equity via evidence-based solutions

### [Experience]{.underline}

::: cv-entry
**Varsity Tutors**

***Math & Statistics Tutor*** &emsp; Remote                       [03/2026 - Present]{.cv-date}

- Tutored individuals and small groups of up to 6 students several times weekly to advance their comprehension of mathematics and statistics topics ranging from basic math literacy to calculus and college-level statistics
:::

::: cv-entry
**Penn Development Research Initiative, DevLab**

***Consulting Data Scientist*** &emsp; Remote                       [09/2024 – Present]{.cv-date}

- Used geospatial raster data and Python-powered computer vision to compare the prevalence of illegal charcoal kiln sites in treatment and comparison areas of Zambia

- Contributed matching weight & regression analyses to the results sections of impact evaluations assessing agroforestry interventions among cocoa farmers in Cote D’Ivoire and Ghana
:::

::: cv-entry
**DataPulse Research**

***Freelance Contributing Data Journalist*** &emsp; Remote                       [03/2025 – 01/2026]{.cv-date}

- Authored short-form articles paired with interactive dashboards to communicate statistical insights on politics, culture, and leisure for a startup web publication

- Scraped and analyzed web data using Python tools like BeautifulSoup, Ibis, Polars, Pandas, & Scikit-learn to generate interactive dashboard visualizations with Panel, Plotly, Leaflet, Datawrapper, and D3.js
:::

::: cv-entry
**Mathematica Policy Research**

***Bilingual Field Data Collector*** &emsp; Springfield, MA                       [10/2025 – 12/2025]{.cv-date}

- Managed 200+ cases for the 2025 Mass ECHOS household finance survey for the Federal Reserve Bank of Boston

- Recruited respondents in-person at their residence using English, Spanish, and relationship-building skills
:::

::: cv-entry
**Center for Social Norms and Behavioral Dynamics, University of Pennsylvania**

***Research Specialist*** &emsp; Philadelphia, PA                       [01/2024 - Present]{.cv-date}

-   Writing and managing the R & Quarto codebase for seven research manuscripts investigating poverty trap mechanisms from a nationally representative survey of more than 6,000 Americans over two time periods

-   Providing policy-relevant insights about trust in institutions & social networks using Exploratory Factor Analysis and uncovering key determinants of perceived intergenerational mobility via machine learning (weighted LASSO)

-   Contributing to novel survey methodology research quantifying respondents’ uncertainty around future income
:::

::: cv-entry
**Stanford SPARQ and the Stanford Cohen Lab**

***Research Assistant*** &emsp; Remote                                [02/2023 - 09/2023]{.cv-date}

-   Used R/RStudio, machine learning techniques (elastic net) and natural language processing to predict changes in over 2,000 participants’ attitudes toward federal welfare

-   Developed a Python/JavaScript text analytics algorithm that gives online survey participants real-time feedback on their communication style for better political discussions

-   Recruited 1,500 college students as online study participants via Qualtrics and an online survey panel
:::

::: cv-entry
**Intersectionality in the Social Mind Lab, Haverford College**

***Research Assistant*** &emsp; Haverford, PA                          [10/2020 - 12/2022]{.cv-date}

-   Used R/RStudio, social network analysis, and text analysis to uncover gender-based diƦerences in more than 600 news articles covering police killings

-   Launched and taught data analysis workshops, mentored new lab members, and presented my work in manuscripts, posters, and presentations
:::

::: cv-entry
**Department of Psychology, Haverford College**

***Research Statistics Teaching Assistant*** &emsp; Haverford, PA                          [01/2022 - 05/2022]{.cv-date}

- Tutored individuals and small groups of up to 10 students 3-4 times weekly to advance their comprehension of statistics, quantitative research methods, and the data analysis software Jamovi
:::

::: cv-entry
**Internal Revenue Service/Coding it Forward**

***Data Analyst Fellow*** &emsp; Remote                          [06/2022 - 08/2022]{.cv-date}

- Selected from 1,600 applicants to join 160 early-career technologists in exploring federal careers

- Empowered my team to prioritize instances of major tax fraud by developing a wealth estimator tool using recent economic research, R/RStudio, Stata, and PostgreSQL

- Presented to senior leadership, including Acting Director of the Ofﬁce of Fraud Enforcement Katie Fox
:::

::: cv-entry
**The Kensington Storefront, Mural Arts Philadelphia**

***Program Facilitator*** &emsp; Philadelphia, PA                          [06/2020 - 09/2021]{.cv-date}

- Supported the mission of Mural Arts, Philadelphia’s pre-eminent arts and behavioral health non-proﬁt, by organizing and teaching a custom introductory Spanish course to more than 30 direct service providers
:::

### [Education]{.underline}

::: cv-entry
**B.S., Psychology Major and Statistics Minor**

Haverford College, Haverford, PA                                  [08/2018 - 12/2022]{.cv-date}

-   Graduated cum laude—3.89 GPA

-   Senior Thesis: “Group Status Identity as a Predictor of Social Dominance Orientation in Children”

-   Organized a Psychology department peer mentorship program in collaboration with Psych. Dept. faculty
:::

::: cv-entry
**Non-Degree Graduate Studies**

University of Pennsylvania, Philadelphia, PA                          [08/2024 - 12/2024]{.cv-date}

- Completed two courses using tuition benefits: Applied Impact Evaluation & Geospatial Data Science in Python

- Cum. GPA: 3.85
::: 

### [Skills]{.underline}

::: cv-entry
**Areas of Expertise**: Statistical Modeling, Causal Inference, Machine Learning, NLP, Survey Design, & Spanish

**Software**: R/RStudio, Python, PostgreSQL, Stata, Qualtrics, JavaScript, HTML, Ubuntu, Excel, & G Suite 
:::
